# Generated by Django 5.0.6 on 2024-07-09 12:27

from django.db import migrations, models

class Migration(migrations.Migration):
    
    initial = True  # Marks this as the initial migration
    
    dependencies = [
        # No dependencies for this migration
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',  # Model name
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Primary key field
                ('name', models.CharField(max_length=50)),  # CharField for name
                ('email', models.EmailField(max_length=254)),  # EmailField for email
                ('desc', models.CharField(max_length=500)),  # CharField for description
                ('phonenumber', models.IntegerField()),  # IntegerField for phone number
            ],
        ),
    ]
