# Generated by Django 5.0.6 on 2024-07-09 14:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),  # Dependency on the previous migration
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',  # Model name being altered
            name='phonenumber',  # Field name being altered
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),  # Updated PhoneNumberField definition
        ),
    ]
