# Generated by Django 5.0.6 on 2024-07-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_product_price'),  # Dependency on the previous migration
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',  # First model: Orders
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),  # AutoField for order_id
                ('items_json', models.CharField(max_length=5000)),  # CharField for JSON items
                ('amount', models.IntegerField(default=0)),  # IntegerField for amount
                ('name', models.CharField(max_length=90)),  # CharField for customer name
                ('email', models.CharField(max_length=90)),  # CharField for customer email
                ('address1', models.CharField(max_length=200)),  # CharField for address line 1
                ('address2', models.CharField(max_length=200)),  # CharField for address line 2
                ('city', models.CharField(max_length=100)),  # CharField for city
                ('state', models.CharField(max_length=100)),  # CharField for state
                ('zip_code', models.CharField(max_length=100)),  # CharField for ZIP code
                ('oid', models.CharField(blank=True, max_length=150)),  # CharField for optional ID
                ('amountpaid', models.CharField(blank=True, max_length=500, null=True)),  # CharField for amount paid
                ('paymentstatus', models.CharField(blank=True, max_length=20)),  # CharField for payment status
                ('phone', models.CharField(default='', max_length=100)),  # CharField for phone number
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',  # Second model: OrderUpdate
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),  # AutoField for update_id
                ('order_id', models.IntegerField(default='')),  # IntegerField for associated order_id
                ('update_desc', models.CharField(max_length=5000)),  # CharField for update description
                ('delivered', models.BooleanField(default=False)),  # BooleanField for delivery status
                ('timestamp', models.DateField(auto_now_add=True)),  # DateField for timestamp
            ],
        ),
    ]
